import { NextPage } from "next";
import Head from "next/head";
import { Component, ReactNode } from "react";
import Footer from "./footer";
import Header from "./header";

type LayoutProps = {
  children: ReactNode;
};

const Layout: NextPage<LayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>It&apos;s Me! Tevis!</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex min-h-screen flex-col items-center justify-start bg-gradient-to-b from-[#2e026d] to-[#15162c] p-6">
        {children}
      </main>
      <Footer />
    </>
  );
};

export default Layout;
